# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ACR and webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1- Checkout
        uses: actions/checkout@v2

      - name: Step 2- Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
              
      - name: Step 4- Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2     
         
     
      - name: Step 6 - build with maven
        run: mvn -B package --file pom.xml

      - name: Step 7 List the current directory
        run: ls -a
        
      - name: Step-8 List the target directory
        run: |
          cd target
          ls -a 

      - name: step-7 ACR login
        uses: azure/docker-login@v1
        with:
          login-server: rahultestwebapp04acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Step 8 - Docker build and push to ACR
        run: |
          docker build . -t rahultestwebapp04acr.azurecr.io/simplewebapp:latest
          docker push rahultestwebapp04acr.azurecr.io/simplewebapp:latest  
          
      - name: list docker image
        run: docker images
 
